use_frameworks!

target 'ASForm_Example' do
  pod 'ASForm', :path => '../'

  pod 'ASProgress', '~> 0.1.0'
  pod 'ASValidator', '~> 0.1.9'
  pod 'ASTextField', '~> 0.1.8'
  pod 'ASLabel', '~> 0.1.4'
  pod 'ASDropDown', '~> 0.1.5'
  pod 'ASMToast', '~> 0.1.1'
  pod 'ASOtpTextField', '~> 0.1.4'
  pod 'ASRadioGroup', '~> 0.1.2'
  pod 'ASButton', '~> 0.1.0'
  
  target 'ASForm_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
